### ISSUE TITLE
We may want to move this out of the ECMA org

### ISSUE THREAD

**Issue by dtex** [EcmaTC53/docs#1]
If our goal is to build a community site, we may need to disassociate it from ECMA. I'm not sure if the requirements for participation in ECMA standards would extend to something like this, but if they do, it would be a hurdle for contributors. What do you think @patrickluthi ?

**Comment by phoddie** [comment]
I'm OK either way, but I do have a preference for keeping it under Ecma as long as it doesn't create a significant hurdle.

The reason I think that's OK is the model of test262. The [test262 repository](https://github.com/tc39/test262) is under the TC39 GitHub account which is Ecma, just like our repository. Anyone can make PRs to that. They require a [CLA](https://github.com/tc39/test262#contributing-to-test262) for contributions from non-members, which is something anyone else hosting this should do to avoid horrible IP issues down-the-road.

FWIW – MDN makes the [licensing of contributions implicit](https://github.com/mdn/content/blob/main/CONTRIBUTING.md#license) which isn't something I'm entirely comfortable with.

**Comment by HipsterBrown** [comment]
I also prefer to keep it under the ECMA TC53 org. I have not added a LICENSE file to this, so I will do that along with creating a CLA prompt for contributors similar to test262. I agree that explicit licensing is preferred in this case. 

I'm assuming we want to use [the same license as test262](https://github.com/tc39/test262/blob/main/LICENSE) for this repo.

**Comment by phoddie** [comment]
> I'm assuming we want to use [the same license as test262](https://github.com/tc39/test262/blob/main/LICENSE) for this repo

That would be the most straightforward. BSD should be fine here. And getting another license approved for use by Ecma would likely take some time.

**Comment by dtex** [comment]
I'm fine with closing this as I do not have strong feelings about the CLA.

**Comment by phoddie** [comment]
Closing.
